import { createRoot } from 'react-dom/client';
import App from './App';
import React from 'react';
// import './index.css';
// import { Provider } from 'react-redux';
// import { store } from './store';
// import { BrowserRouter } from 'react-router-dom';
const rootElement = document.getElementById('app');
const root = createRoot(rootElement);
root.render(<App />);
